/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.umg.api.view;

/**
 *
 * @author MK
 * 
 */

import java.awt.Color;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import com.umg.api.model.CursosModel;
import com.umg.api.service.CursosService;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class CursosView extends javax.swing.JInternalFrame {
 
    /**
     * Creates new form FrmEmpleados
     */
    private CursosService service = new CursosService();

    private final JPanel[] paneles;
    String[] columnas = {"ID", "Id Teacher", "Nombre", "Codigo", "Modalidad", "Credito"};
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);
    public CursosView() {
        CursosModel data;
        initComponents();
        updateTable();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        tbl.setModel(modelo);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        tbl.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void  valueChanged (ListSelectionEvent e){
                fillFieldsFromSelectedRow();
            }
        });
        txtId_Curso.setEnabled(false);

            cleanCampos();
        
// <editor-fold defaultstate="collapsed" desc="Configuraciones de Botones">
    paneles = new JPanel[] { btnCrear, btnBuscar, btnActualizar, btnEliminar, btnLimpiar, btnMostrarTodos }; 
    Color colorNormal = new Color(71,13,188);  
    Color colorHover = new Color(115,67,210);

        for (JPanel panel : paneles) {
            panel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                    panel.setBackground(colorHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                    panel.setBackground(colorNormal);
            }
            });

        }// </editor-fold>
    
    }

    private void fillFieldsFromSelectedRow() {
    int row = tbl.getSelectedRow(); // tu JTable
    if (row != -1) {
        int id = (int) modelo.getValueAt(row, 0);
        txtId_Curso.setText(String.valueOf(id));
        txtIdTeacher.setText(String.valueOf(modelo.getValueAt(row, 1)));
        txtNombre.setText((String) modelo.getValueAt(row, 2));
        txtCodigo.setText((String) modelo.getValueAt(row, 3));
        txtMod.setText((String) modelo.getValueAt(row, 4));
        txtCredito.setText(String.valueOf(modelo.getValueAt(row, 5)));
        
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId_Curso = new javax.swing.JTextField();
        txtIdTeacher = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        btnCrear = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnMostrarTodos = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtMod = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtCredito = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1042, 776));
        setMinimumSize(new java.awt.Dimension(1042, 776));
        setPreferredSize(new java.awt.Dimension(1042, 776));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(1030, 740));
        background.setMinimumSize(new java.awt.Dimension(1030, 740));
        background.setPreferredSize(new java.awt.Dimension(1030, 740));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("ID:");
        jLabel10.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel10.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel10.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Id Teacher");
        jLabel1.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jLabel2.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtId_Curso.setBackground(new java.awt.Color(255, 255, 255));
        txtId_Curso.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtId_Curso.setForeground(new java.awt.Color(204, 204, 204));
        txtId_Curso.setBorder(null);
        txtId_Curso.setMinimumSize(new java.awt.Dimension(300, 26));
        txtId_Curso.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtId_Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        txtIdTeacher.setBackground(new java.awt.Color(255, 255, 255));
        txtIdTeacher.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtIdTeacher.setForeground(new java.awt.Color(204, 204, 204));
        txtIdTeacher.setBorder(null);
        txtIdTeacher.setMinimumSize(new java.awt.Dimension(300, 26));
        txtIdTeacher.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtIdTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setBorder(null);
        txtNombre.setMinimumSize(new java.awt.Dimension(300, 26));
        txtNombre.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jScrollPane1.setBorder(null);

        tbl.setBackground(new java.awt.Color(255, 255, 255));
        tbl.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        tbl.setForeground(new java.awt.Color(204, 204, 204));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {}
        ));
        tbl.setFocusable(false);
        jScrollPane1.setViewportView(tbl);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 20, 520, 700));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator3.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator5.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator5.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator6.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator6.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator12.setMaximumSize(new java.awt.Dimension(1010, 11));
        jSeparator12.setMinimumSize(new java.awt.Dimension(1010, 11));
        jSeparator12.setPreferredSize(new java.awt.Dimension(1010, 11));
        background.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 10, 10, 710));

        btnCrear.setBackground(new java.awt.Color(71, 13, 188));
        btnCrear.setMaximumSize(new java.awt.Dimension(140, 40));
        btnCrear.setMinimumSize(new java.awt.Dimension(140, 40));
        btnCrear.setPreferredSize(new java.awt.Dimension(140, 40));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Agregar");

        javax.swing.GroupLayout btnCrearLayout = new javax.swing.GroupLayout(btnCrear);
        btnCrear.setLayout(btnCrearLayout);
        btnCrearLayout.setHorizontalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11))
        );
        btnCrearLayout.setVerticalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11))
        );

        background.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 340, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(71, 13, 188));
        btnActualizar.setMaximumSize(new java.awt.Dimension(140, 40));
        btnActualizar.setMinimumSize(new java.awt.Dimension(140, 40));
        btnActualizar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Actualizar");

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12))
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel12))
        );

        background.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 490, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(71, 13, 188));
        btnBuscar.setMaximumSize(new java.awt.Dimension(140, 40));
        btnBuscar.setMinimumSize(new java.awt.Dimension(140, 40));
        btnBuscar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Buscar");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel13))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel13))
        );

        background.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 390, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(71, 13, 188));
        btnEliminar.setMaximumSize(new java.awt.Dimension(140, 40));
        btnEliminar.setMinimumSize(new java.awt.Dimension(140, 40));
        btnEliminar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel14))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14))
        );

        background.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 440, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(71, 13, 188));
        btnLimpiar.setMaximumSize(new java.awt.Dimension(140, 40));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(140, 40));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Limpiar");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel15))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel15))
        );

        background.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 540, -1, -1));

        btnMostrarTodos.setBackground(new java.awt.Color(71, 13, 188));
        btnMostrarTodos.setMaximumSize(new java.awt.Dimension(140, 40));
        btnMostrarTodos.setMinimumSize(new java.awt.Dimension(140, 40));
        btnMostrarTodos.setPreferredSize(new java.awt.Dimension(140, 40));
        btnMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarTodosMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mostrar todos");

        javax.swing.GroupLayout btnMostrarTodosLayout = new javax.swing.GroupLayout(btnMostrarTodos);
        btnMostrarTodos.setLayout(btnMostrarTodosLayout);
        btnMostrarTodosLayout.setHorizontalGroup(
            btnMostrarTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarTodosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16))
        );
        btnMostrarTodosLayout.setVerticalGroup(
            btnMostrarTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarTodosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel16))
        );

        background.add(btnMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 590, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(204, 204, 204));
        txtCodigo.setBorder(null);
        txtCodigo.setMinimumSize(new java.awt.Dimension(300, 26));
        txtCodigo.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Codigo:");
        jLabel3.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator7.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator7.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        txtMod.setBackground(new java.awt.Color(255, 255, 255));
        txtMod.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtMod.setForeground(new java.awt.Color(204, 204, 204));
        txtMod.setBorder(null);
        txtMod.setMinimumSize(new java.awt.Dimension(300, 26));
        txtMod.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator8.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator8.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Modalidad:");
        jLabel4.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel4.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel4.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtCredito.setBackground(new java.awt.Color(255, 255, 255));
        txtCredito.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtCredito.setForeground(new java.awt.Color(204, 204, 204));
        txtCredito.setBorder(null);
        txtCredito.setMinimumSize(new java.awt.Dimension(300, 26));
        txtCredito.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator9.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator9.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Credito:");
        jLabel5.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel5.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel5.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
    try {
        CursosModel data = new CursosModel();
        data.setTeacherId(Integer.parseInt(txtIdTeacher.getText()));
        data.setNombre(txtNombre.getText());
        data.setCodigo(txtCodigo.getText());
        data.setModalidad(txtMod.getText());
        data.setCredito(Float.parseFloat(txtCredito.getText()));

        CursosService service = new CursosService();
        service.create(data);

        JOptionPane.showMessageDialog(this, "Info agregado correctamente ✅");
        updateTable();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al agregar Info: " + e.getMessage());
    }

    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        try {
            int id = Integer.parseInt(txtId_Curso.getText());
            CursosModel data = new CursosModel();
            data.setTeacherId(Integer.parseInt(txtIdTeacher.getText()));
            data.setNombre(txtNombre.getText());
            data.setCodigo(txtCodigo.getText());
            data.setModalidad(txtMod.getText());
            data.setCredito(Float.parseFloat(txtCredito.getText()));
            
            service.update(id, data); // Método del Service
            JOptionPane.showMessageDialog(this, "Info actualizado correctamente ✅");
            updateTable();
            cleanCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar Info: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        try {
            int id = Integer.parseInt(txtId_Curso.getText().trim());
            modelo.setRowCount(0); // Limpiar tabla

            CursosModel t = service.getOne(id);
            if (t != null) {
                modelo.addRow(new Object[]{
                    t.getId_curso(),
                    t.getTeacherId(),
                    t.getNombre(),
                    t.getCodigo(),
                    t.getModalidad(),
                    t.getCredito()
                });
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un Info con ID " + id);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID válido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar Info: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            int id = Integer.parseInt(txtId_Curso.getText());
            service.delete(id);
            JOptionPane.showMessageDialog(this, "Info eliminado correctamente ✅");
            updateTable();
            cleanCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar Info: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        cleanCampos();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnMostrarTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTodosMouseClicked
        updateTable();
    }//GEN-LAST:event_btnMostrarTodosMouseClicked

private void cleanCampos() {
    txtId_Curso.setText("");
    txtNombre.setText("");
    txtCodigo.setText("");
    txtIdTeacher.setText("");

}

private void updateTable() {
    modelo.setRowCount(0); // Limpiar tabla
    try {
        List<CursosModel> data = service.getAll();
        for (CursosModel t : data) {
            modelo.addRow(new Object[]{
                t.getId_curso(),
                t.getTeacherId(),
                t.getNombre(),
                t.getCodigo(),
                t.getModalidad(),
                t.getCredito()
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar tabla: " + e.getMessage());
    }
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCrear;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnMostrarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtIdTeacher;
    private javax.swing.JTextField txtId_Curso;
    private javax.swing.JTextField txtMod;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
