/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.umg.api.view;


/**
 *
 * @author MK
 */
public class Initial_Internal_Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Init
     */
    public Initial_Internal_Frame() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Descr_1 = new javax.swing.JLabel();
        Descr_2 = new javax.swing.JLabel();
        Descr_3 = new javax.swing.JLabel();
        Descr_4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 740));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1030, 740));

        Welcome.setBackground(new java.awt.Color(0, 0, 0));
        Welcome.setFont(new java.awt.Font("Roboto Medium", 0, 78)); // NOI18N
        Welcome.setForeground(new java.awt.Color(51, 51, 255));
        Welcome.setText("Bienvenido");

        Descr_1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_1.setForeground(new java.awt.Color(0, 0, 0));
        Descr_1.setText("Sistema de Notas. Controla,");

        Descr_2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_2.setForeground(new java.awt.Color(0, 0, 0));
        Descr_2.setText("administre y las notas de formas mas eficazes!!");

        Descr_3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_3.setForeground(new java.awt.Color(0, 0, 0));
        Descr_3.setText("Este sistema le permitira mejorar el control de forma detallada y consisa de su centro estudiantil.");

        Descr_4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_4.setForeground(new java.awt.Color(0, 0, 0));
        Descr_4.setText("Podrá acceder a las diversas herramientas para sus necesidades especificas.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Welcome)
                    .addComponent(Descr_1)
                    .addComponent(Descr_2)
                    .addComponent(Descr_3)
                    .addComponent(Descr_4))
                .addGap(317, 317, 317))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(Welcome)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descr_1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Descr_2)))
                .addGap(18, 18, 18)
                .addComponent(Descr_3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Descr_4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descr_1;
    private javax.swing.JLabel Descr_2;
    private javax.swing.JLabel Descr_3;
    private javax.swing.JLabel Descr_4;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
